# Generated by Django 3.0 on 2021-12-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_lettings_site", "0003_auto_20211221_1905"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
