# Generated by Django 3.0 on 2021-12-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_lettings_site", "0004_delete_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="Letting",
        ),
    ]
